# Generated by Django 5.2 on 2025-04-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appliedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedto',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=30),
        ),
    ]
